# Generated by Django 3.0.7 on 2020-08-04 03:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('url', models.ImageField(upload_to='', verbose_name='图片地址')),
            ],
            options={
                'verbose_name': '图片表',
                'verbose_name_plural': '图片表',
            },
        ),
        migrations.CreateModel(
            name='LeaveMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('headingImg', models.IntegerField(verbose_name='留言头像')),
                ('content', models.TextField(verbose_name='留言内容')),
                ('nickName', models.CharField(max_length=64, unique=True, verbose_name='昵称')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('city', models.CharField(max_length=64, verbose_name='城市')),
            ],
            options={
                'verbose_name': '留言表',
                'verbose_name_plural': '留言表',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('songName', models.CharField(max_length=64, verbose_name='音乐名称')),
                ('kind', models.CharField(max_length=64, verbose_name='流派')),
                ('songUrl', models.CharField(max_length=600, verbose_name='音乐链接')),
            ],
            options={
                'verbose_name': '音乐表',
                'verbose_name_plural': '音乐表',
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('websiteReadPerson', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '浏览记录表',
                'verbose_name_plural': '浏览记录表',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('name', models.CharField(max_length=64, verbose_name='标签')),
            ],
            options={
                'verbose_name': '标签表',
                'verbose_name_plural': '标签表',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('subName', models.CharField(max_length=64, verbose_name='该集名称')),
                ('url', models.CharField(max_length=600, verbose_name='视频链接')),
            ],
            options={
                'verbose_name': '动漫表-单集',
                'verbose_name_plural': '动漫表-单集',
            },
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('title', models.CharField(max_length=64, verbose_name='段落标题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='段落内容-文字')),
                ('code', models.CharField(blank=True, max_length=600, null=True, verbose_name='代码')),
                ('imgs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog2020.Img', verbose_name='图片')),
            ],
            options={
                'verbose_name': '段落表',
                'verbose_name_plural': '段落表',
            },
        ),
        migrations.CreateModel(
            name='Cartoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('mainName', models.CharField(max_length=64, verbose_name='动漫名称')),
                ('simpleIntroduce', models.TextField(verbose_name='动漫简介')),
                ('totalNum', models.IntegerField(default=12, verbose_name='集数')),
                ('videoInfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog2020.Video', verbose_name='视频URL')),
            ],
            options={
                'verbose_name': '动漫表',
                'verbose_name_plural': '动漫表',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('title', models.CharField(max_length=64, verbose_name='博客名')),
                ('subTitle', models.CharField(max_length=64, verbose_name='副标题')),
                ('gitHubUrl', models.CharField(max_length=600, verbose_name='Github网址')),
                ('blogReadPerson', models.IntegerField(default=0, verbose_name='阅读人数')),
                ('leavePassage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog2020.LeaveMessage', verbose_name='留言')),
                ('passage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog2020.Passage', verbose_name='段落')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog2020.Tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '博客表',
                'verbose_name_plural': '博客表',
            },
        ),
    ]
