# Generated by Django 3.0.7 on 2020-08-04 04:03

import blog2020.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2020', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to='blogImg', verbose_name='图片地址'),
        ),
        migrations.AlterField(
            model_name='leavemessage',
            name='headingImg',
            field=models.ImageField(default=blog2020.models.RandomHeadingImg, upload_to='headingImg', verbose_name='留言头像'),
        ),
    ]
