# Generated by Django 3.0.7 on 2020-08-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2020', '0002_auto_20200804_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='gitHubUrl',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Github网址'),
        ),
        migrations.AlterField(
            model_name='leavemessage',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='leavemessage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱'),
        ),
    ]
