# Generated by Django 3.0.7 on 2020-08-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2020', '0003_auto_20200804_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='name',
            field=models.CharField(default='WebRecording', max_length=64, verbose_name='名称'),
        ),
    ]
