# Generated by Django 3.0.7 on 2020-08-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2020', '0004_recording_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='author',
            field=models.CharField(default=2, max_length=128, verbose_name='作者'),
            preserve_default=False,
        ),
    ]
