# Generated by Django 3.0.7 on 2020-08-09 02:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog2020', '0006_leavemessage_replyname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('replyName', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='回复者')),
                ('content', models.TextField(verbose_name='留言内容')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('city', models.CharField(blank=True, max_length=64, null=True, verbose_name='城市')),
            ],
            options={
                'verbose_name': '留言回复表',
                'verbose_name_plural': '留言回复表',
            },
        ),
        migrations.RemoveField(
            model_name='leavemessage',
            name='replyName',
        ),
        migrations.AddField(
            model_name='leavemessage',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog2020.ReplyMessage', verbose_name='回复'),
        ),
    ]
