# Generated by Django 3.0.7 on 2020-08-09 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog2020', '0007_auto_20200809_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavemessage',
            name='reply',
        ),
        migrations.AddField(
            model_name='replymessage',
            name='leave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog2020.LeaveMessage', verbose_name='留言'),
        ),
    ]
