# Generated by Django 3.0.7 on 2020-08-09 12:06

import blog2020.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2020', '0011_auto_20200809_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='replymessage',
            name='headingImg',
            field=models.ImageField(default=blog2020.models.RandomHeadingImg, upload_to='headingImg', verbose_name='留言头像'),
        ),
    ]
