# Generated by Django 3.0.7 on 2020-08-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2020', '0012_replymessage_headingimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='passage',
        ),
        migrations.AddField(
            model_name='blog',
            name='passage',
            field=models.ManyToManyField(blank=True, null=True, to='blog2020.Passage', verbose_name='段落'),
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tag',
        ),
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='blog2020.Tag', verbose_name='标签'),
        ),
    ]
