# Generated by Django 3.0.7 on 2020-08-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2020', '0013_auto_20200812_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passage',
            name='imgs',
        ),
        migrations.AddField(
            model_name='passage',
            name='imgs',
            field=models.ManyToManyField(blank=True, null=True, to='blog2020.Img', verbose_name='图片'),
        ),
    ]
