# Generated by Django 3.0.7 on 2020-08-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2020', '0014_auto_20200813_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='leavePassage',
        ),
        migrations.AddField(
            model_name='leavemessage',
            name='owner',
            field=models.CharField(choices=[(1, 'Me'), (2, 'Blog')], default=1, max_length=16, verbose_name='属于'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='passage',
            field=models.ManyToManyField(blank=True, to='blog2020.Passage', verbose_name='段落'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(blank=True, to='blog2020.Tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='passage',
            name='imgs',
            field=models.ManyToManyField(blank=True, to='blog2020.Img', verbose_name='图片'),
        ),
    ]
