# Generated by Django 3.0.7 on 2020-08-19 06:38

import blog2020.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2020', '0017_auto_20200813_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='author',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='songUrl',
            new_name='src',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='songName',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='music',
            name='kind',
        ),
        migrations.AddField(
            model_name='music',
            name='lrc',
            field=models.CharField(blank=True, max_length=624, null=True, verbose_name='歌词'),
        ),
        migrations.AddField(
            model_name='music',
            name='pic',
            field=models.ImageField(blank=True, default=blog2020.models.RandomHeadingImg, null=True, upload_to='musicImg', verbose_name='留言头像'),
        ),
        migrations.AlterField(
            model_name='leavemessage',
            name='owner',
            field=models.IntegerField(default=1, verbose_name='属于'),
        ),
        migrations.AlterField(
            model_name='replymessage',
            name='owner',
            field=models.IntegerField(default=1, verbose_name='属于'),
        ),
    ]
