# Generated by Django 3.0.7 on 2020-08-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2020', '0018_auto_20200819_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoon',
            name='videoImg',
            field=models.ImageField(blank=True, null=True, upload_to='videoImg', verbose_name='动漫图片'),
        ),
    ]
