# Generated by Django 3.0.7 on 2020-08-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2020', '0019_cartoon_videoimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoon',
            name='kind',
            field=models.CharField(choices=[('advice', '推荐'), ('like', '喜欢')], default='advice', max_length=12, verbose_name='属于'),
        ),
    ]
