# Generated by Django 3.0.7 on 2020-07-19 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20200713_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='written',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='written_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(default='img/default.jpg', upload_to='img/%Y/%m/%d/', verbose_name='图片'),
        ),
    ]
